# Generated by Django 5.1.6 on 2025-06-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequetsFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_ippis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loam_fee', to='accounts.member')),
            ],
        ),
    ]
