# Generated by Django 5.1.6 on 2025-07-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanformfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanformfee',
            old_name='amount',
            new_name='form_fee',
        ),
    ]
