# Generated by Django 5.1.6 on 2025-06-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanrequetsfee_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequetsfee',
            name='member_ippis',
            field=models.IntegerField(),
        ),
    ]
