# Generated by Django 5.1.6 on 2025-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='local_government_area',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='full_names',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='phone_no',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='religion',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
