# Generated by Django 5.1.6 on 2025-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savings',
            index=models.Index(fields=['member', 'month'], name='main_saving_member__af1069_idx'),
        ),
    ]
